import {
  VEHICLE_STATES,
  DRIVER_STATES,
  ASSIGNMENT_OPERATIONAL_STATES,
  WORK_OPERATIONAL_STATES,
  ROUTE_STATES
} from "./states"

export const VEHICLE_TRANSITIONS = {

  [VEHICLE_STATES.AVAILABLE]: [
    VEHICLE_STATES.ASSIGNED
  ],

  [VEHICLE_STATES.ASSIGNED]: [
    VEHICLE_STATES.IN_ROUTE,
    VEHICLE_STATES.AVAILABLE,
    VEHICLE_STATES.DAMAGED
  ],

  [VEHICLE_STATES.IN_ROUTE]: [
    VEHICLE_STATES.AVAILABLE,
    VEHICLE_STATES.DAMAGED
  ],

  [VEHICLE_STATES.DAMAGED]: [
    VEHICLE_STATES.MAINTENANCE
  ],

  [VEHICLE_STATES.MAINTENANCE]: [
    VEHICLE_STATES.AVAILABLE
  ]
}

export const DRIVER_TRANSITIONS = {

  [DRIVER_STATES.AVAILABLE]: [
    DRIVER_STATES.ASSIGNED
  ],

  [DRIVER_STATES.ASSIGNED]: [
    DRIVER_STATES.IN_ROUTE,
    DRIVER_STATES.AVAILABLE
  ],

  [DRIVER_STATES.IN_ROUTE]: [
    DRIVER_STATES.AVAILABLE,
    DRIVER_STATES.RETURNING
  ],

  [DRIVER_STATES.RETURNING]: [
    DRIVER_STATES.AVAILABLE
  ]
}

export const ASSIGNMENT_TRANSITIONS = {

  [ASSIGNMENT_OPERATIONAL_STATES.CONFIRMED]: [
    ASSIGNMENT_OPERATIONAL_STATES.ACTIVE,
    ASSIGNMENT_OPERATIONAL_STATES.ABORTED
  ],

  [ASSIGNMENT_OPERATIONAL_STATES.ACTIVE]: [
    ASSIGNMENT_OPERATIONAL_STATES.FINISHED
  ]
}

export const WORK_TRANSITIONS = {

  [WORK_OPERATIONAL_STATES.PENDING]: [
    WORK_OPERATIONAL_STATES.ASSIGNED
  ],

  [WORK_OPERATIONAL_STATES.ASSIGNED]: [
    WORK_OPERATIONAL_STATES.IN_PROGRESS,
    WORK_OPERATIONAL_STATES.PENDING
  ],

  [WORK_OPERATIONAL_STATES.IN_PROGRESS]: [
    WORK_OPERATIONAL_STATES.FINISHED
  ]
}

export const ROUTE_TRANSITIONS = {

  [ROUTE_STATES.ACTIVE]: [
    ROUTE_STATES.RETURNING
  ],

  [ROUTE_STATES.RETURNING]: [
    ROUTE_STATES.FINISHED
  ]
}